// <auto-generated />
using System;
using GerFinancas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerFinancas.Migrations
{
    [DbContext(typeof(GerFinancasContext))]
    [Migration("20220718223508_Criado novo banco MySql")]
    partial class CriadonovobancoMySql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("GerFinancas.Models.Cartoes", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<double>("Limite")
                        .HasColumnType("double");

                    b.Property<int>("MelhorDiaCompra")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("GerFinancas.Models.FormatoLancamento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Codigo");

                    b.ToTable("FormatoLancamentos");
                });

            modelBuilder.Entity("GerFinancas.Models.Lancamentos", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReceitaDespesa")
                        .HasColumnType("int");

                    b.Property<int>("TipoCodigo")
                        .HasColumnType("int");

                    b.Property<int>("TipoDoLancamento")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Codigo");

                    b.HasIndex("TipoCodigo");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("GerFinancas.Models.TipoLancamento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Codigo");

                    b.ToTable("TipoLancamento");
                });

            modelBuilder.Entity("GerFinancas.Models.UsuarioLogin", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Codigo");

                    b.ToTable("UsuarioLogin");
                });

            modelBuilder.Entity("GerFinancas.Models.Lancamentos", b =>
                {
                    b.HasOne("GerFinancas.Models.TipoLancamento", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });
#pragma warning restore 612, 618
        }
    }
}
