// <auto-generated />
using System;
using GerFinancas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerFinancas.Migrations
{
    [DbContext(typeof(GerFinancasContext))]
    partial class GerFinancasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GerFinancas.Models.Cartoes", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<double>("Limite")
                        .HasColumnType("float");

                    b.Property<int>("MelhorDiaCompra")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("GerFinancas.Models.Lancamentos", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceitaDespesa")
                        .HasColumnType("int");

                    b.Property<int>("TipoCodigo")
                        .HasColumnType("int");

                    b.Property<int>("TipoDoLancamento")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Codigo");

                    b.HasIndex("TipoCodigo");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("GerFinancas.Models.TipoLancamento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("TipoLancamento");
                });

            modelBuilder.Entity("GerFinancas.Models.Lancamentos", b =>
                {
                    b.HasOne("GerFinancas.Models.TipoLancamento", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });
#pragma warning restore 612, 618
        }
    }
}
